# TV TEST DATA
TVCLIENT = 'TVTestClient'
TVCODE_CLIENT = 'TVTESTCLIENT'

TVBRAND = 'TVTestBrand'
TVCODE_BRAND = 'TVTSTBRND'

TVPRODUCT = 'TVTestProduct'
TVCODE_PRODUCT = 'TVTSTPRDCT'

# DIGITAL TEST DATA
DIGITAL_CLIENT_NAME = 'Autotest Client'
DIGITAL_CLIENT_NAMING = 'AUTOTESTC'
DIGITAL_CLIENT_NAME2 = 'Autotest Client2'
DIGITAL_CLIENT_NAMING2 = 'AUTOTESTC2'

DIGITAL_BRAND_NAME = 'Autotest Brand'
DIGITAL_BRAND_NAMING = 'AUTOTESTB'
DIGITAL_BRAND_NAME2 = 'Autotest Brand2'
DIGITAL_BRAND_NAMING2 = 'AUTOTESTB2'

DIGITAL_PRODUCT_NAME = 'Autotest Product'
DIGITAL_PRODUCT_NAMING = 'AUTOTESTP'
DIGITAL_PRODUCT_NAME2 = 'Autotest Product2'
DIGITAL_PRODUCT_NAMING2 = 'AUTOTESTP2'

DIGITAL_CO_BRAND_NAME = 'Autotest CoBrand'
DIGITAL_CO_BRAND_NAMING = 'AUTOTESTCB'
DIGITAL_CO_BRAND_NAME2 = 'Autotest CoBrand2'
DIGITAL_CO_BRAND_NAMING2 = 'AUTOTSTCB2'

DIGITAL_AGENCY_NAME = 'Autotest Agency'
DIGITAL_AGENCY_NAMING = 'AUTOTESTA'
DIGITAL_AGENCY_NAME2 = 'Autotest Agency2'
DIGITAL_AGENCY_NAMING2 = 'AUTOTESTA2'

DIGITAL_DEPARTMENT_NAME = 'Autotest Department'
DIGITAL_DEPARTMENT_NAMING = 'AUTOTESTD'

DIGITAL_AGE_NAME = '18-24'
DIGITAL_AGE_NAME2 = '25-35'

DIGITAL_GENDER_NAME = 'Женщины'
DIGITAL_GENDER_NAME2 = 'Мужчины'

DIGITAL_INCOME_NAME = 'Средний'
DIGITAL_INCOME_NAME2 = 'Высокий'

DIGITAL_KIDS_NAME = 'Планируются'
DIGITAL_KIDS_NAME2 = 'Дети до года'

DIGITAL_MARTIAL_NAME = 'Не состоят в браке'
DIGITAL_MARTIAL_NAME2 = 'Состоят в браке'

DIGITAL_CITY_CODE = 'msk'
DIGITAL_CITY_CODE2 = 'spb'

DIGITAL_FCT_SEGMENT_NAMING = 'cats'
DIGITAL_FCT_SEGMENT_NAMING2 = 'dogs'
DIGITAL_INT_SEGMENT_NAMING = 'parrots'
DIGITAL_INT_SEGMENT_NAMING2 = 'canary'
DIGITAL_OWN_SEGMENT_NAMING = 'houseowner'
DIGITAL_OWN_SEGMENT_NAMING2 = 'houseowner'

DIGITAL_GOAL_BRAND_CODE = 'BRAND'
DIGITAL_GOAL_CONSD_CODE = 'CONSD'

DIGITAL_AD_FORMAT_INSTREAM_BUMPER_ADS_NAME = 'Видео. Instream: Bumper Ads'
DIGITAL_AD_FORMAT_NAMING = 'html5pl'
DIGITAL_AD_SIZE_1000X120_NAME = '1000x120'
DIGITAL_AD_SIZE_1000X250_NAME = '1000x250'
DIGITAL_AD_SIZE_NAMING = '1170x200'
DIGITAL_BUY_TYPE_NAMING_CPM = 'cpm'
DIGITAL_BUY_TYPE_CPM_NAME = 'CPM'
DIGITAL_BUY_TYPE_VCPM_NAME = 'VCPM'
DIGITAL_CHANNEL_OLV_NAME = 'OLV'
DIGITAL_PLACEMENT_TYPE_NAME = 'Динамика'
DIGITAL_PRICE_METRIC_CPM_NAME = 'CPM'
DIGITAL_SELLER_NAMING_MTS = 'mts'
DIGITAL_SELLER_MTS_NAME = 'МТС'
DIGITAL_SELLER_NAMING_YA = 'yandex'
DIGITAL_SOURCE_MTS_DSP_NAME = 'МТС DSP'
DIGITAL_SOURCE_NAMING_MTS_DSP = 'mtsdsp'
DIGITAL_SOURCE_NAMING_YD = 'ydirect'
DIFITAL_SOURCE_NAMING_APF = 'aflr'
DIFITAL_SOURCE_NAMING_ADRVR = 'arvr'
DIGITAL_SOURCE_NAMING_YM = 'ym'
DIGITAL_ITOOL_CODE_MTS_DSP = 'MTSDSP'
DIGITAL_ITOOL_CODE_YM = 'YM'
DIGITAL_CHANNEL_NAMING = 'dis'
DIGITAL_METRIC_CODE_BUDGET = 'BUDGET'
DIGITAL_METRIC_BUDGET_NAME = 'Бюджет'
DIGITAL_METRIC_CODE_FREQ = 'FREQ'
DIGITAL_METRIC_CODE_CTR = 'CTR'
DIGITAL_METRIC_CODE_VTR = 'VTR'
DIGITAL_IMPS_METRIC_CODE = 'IMPS'
DIGITAL_CLICKS_METRIC_CODE = 'CLICKS'
DIGITAL_CLICKS_METRIC_VIEWS = 'VIEWS'
DIGITAL_PRODUCT_CATEGORY_CODE = 'compu'
DIGITAL_PRODUCT_TYPE_CODE = 'GC'
DIGITAL_SOURCE_MY_TARGET_NAME = 'MyTarget'
DIGITAL_FORMAT_HTML5_NAME = 'HTML5'
DIGITAL_BENCHMARK_METRIC_CTR_NAME = 'CTR'
DIGITAL_CHANNEL_DISPLAY_NAME = 'Display'
DIGITAL_SITE_YM_NAME = 'Яндекс метрика'
DIGITAL_SITE_YD_NAME = 'Яндекс Директ'
DIGITAL_POST_CLICK_APPSFLYER_NAME = 'appsFlyer'
DIGITAL_APPSFLYER_ACC = 'TestAccAppsFlyer'
DIGITAL_IN_APP_EVENT = 'TestInAppEvent'
DIGITAL_POST_CLICK_APP = 'МТС GOODOK'
DIGITAL_PLACEMENT_TYPE_DIN_NAME = 'Динамика'
DIGITAL_AD_SIZE_1160X150_NAME = '1160x150'
DIGITAL_PLACEMENT_PLATFORM_DESKTOP_NAME = 'Десктоп'

# Информация для кампаний
MARKET_TARGETS = 'Цели рекламной кампании'
TARGET_AUDIENCE = 'Целевая аудитория'
CONDITIONS = 'Требования и ограничения'
CONDITIONS_DESCRIPTION_TEXT = 'This is a condition description text'
GEO_TARGETING_DESCRIPTION_TEXT = 'This is a geo targeting description text'
TARGET_AUDIENCE_DESCRIPTION_TEXT = 'This is a target audience description text'
BASE_TARGETING_DESCRIPTION_TEXT = 'This is a base target description text'

# Статусы кампаний
DRAFT_STATUS = 'Черновик'
PLANNING_STATUS = 'Планирование'
APPROVED_STATUS = 'Утверждена'

# Статусы медиаплана
APPROVED_MP_STATUS = 'Утвержден'
PLANNING_MP_STATUS = 'Планирование'

# Статусы размещений
IN_PROGRESS_PLACEMENT_STATUS = 'В работе'
FILLED_PLACEMENT_STATUS = 'Заполнено'
PUBLISHED_PLACEMENT_STATUS = 'Опубликовано'

# Методы настроек подключений
DIGITAL_CONNECTIONS_ITEM_METHOD_MANUAL = 'Ручное'
DIGITAL_CONNECTIONS_ITEM_METHOD_AUTO = 'Автоматическое'
DIGITAL_CONNECTIONS_ITEM_NOT_USED = 'Не используется'
DIGITAL_POST_CLICK_COUNTER_ID_1 = '1000'
DIGITAL_POST_CLICK_COUNTER_ID_2 = '123456789'
DIGITAL_POST_CLICK_COUNTER_ID_3 = '219235111'
# TODO: https://jira.mts.ru/browse/MDP-6435

# Типы кампаний
TV_TYPE = 'ТВ'
DIGITAL_TYPE = 'Digital'
GOAL_TV = 'Brand awareness (Top of mind)'
# ссылки на лендинг
DIGITAL_LANDING_LINK = 'https://yandex.ru'
DIGITAL_LANDING_LINK_ALT = 'https://mail.ru/'

PATTERN_ID = r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

# Взаимодействие с Excel
SIMPLE_MPLAN_XLS_EXPORT = 'simple_mplan_xls_export.xlsx'
MAIN_TAB = 'Медиаплан Total'

EMAIL_ORGANIZATION = 'qa-admin@sknt.ru'
